name: AppMap Analysis

on:
    workflow_call:

jobs:
    analyze:
        runs-on: ubuntu-latest
        permissions: write-all

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Install AppMap tools
              uses: getappmap/install-action@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  install-appmap-library: false

            - name: Restore AppMaps
              uses: actions/cache/restore@v3
              with:
                  path: build/appmap
                  key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

            - name: Archive AppMaps
              if: github.event_name != 'pull_request'
              uses: getappmap/archive-action@main

            - name: Analyze AppMaps
              uses: getappmap/analyze-action@main
              if: github.event_name == 'pull_request'
              with:
                  base-revision: ${{ github.event.pull_request.base.sha }}
                  head-revision: ${{ github.event.pull_request.head.sha }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
