name: Build
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
    pull_request:
    push:
        branches:
            - develop
    schedule:
        - cron: "0 0 * * 0"

jobs:
    test:
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest ]

        name: Test ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        timeout-minutes: 45
        steps:
            - name: Fetch Sources
              uses: actions/checkout@v4

            - name: Gradle Wrapper Validation
              uses: gradle/actions/wrapper-validation@v3

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 21

            # https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-github-actions
            - name: Show GitHub Actions rate limit
              shell: bash
              # curl is unavailable on Windows
              if: runner.os != 'Windows'
              run: |
                  curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -i https://api.github.com/users/octocat | grep x-ratelimit

            - name: Run Linters and Tests
              shell: bash
              run: ./gradlew check

            - name: Verify plugin
              shell: bash
              run: ./gradlew verifyPluginProjectConfiguration

            - name: Run Plugin Verifier
              shell: bash
              # JetBrains plugin verifier should always report the same results, regardless of the OS
              if: runner.os == 'Linux'
              run: ./gradlew verifyPlugin

            - name: Upload Test Reports
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: test-reports-${{ matrix.os }}
                  path: |
                      build/reports/
                      **/build/reports/

            - name: Save AppMaps
              uses: actions/cache/save@v4
              if: runner.os == 'Linux'
              with:
                  path: ./tmp/appmap
                  key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

    appmap-analysis:
        if: always()
        needs: [test]
        uses: getappmap/analyze-action/.github/workflows/appmap-analysis.yml@v1
        permissions:
          actions: read
          contents: read
          checks: write
          pull-requests: write
