name: Build
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    JAVA_VERSION: 21
on:
    pull_request:
    push:
        branches:
            - develop
    schedule:
        - cron: "0 0 * * 0"

jobs:
    test:
        strategy:
            matrix:
                platform_version: [ "241" ]
                os: [ ubuntu, windows, macos ]
                include:
                    # Run tests with latest platform version, but only on Linux
                    - platform_version: "253"
                      os: ubuntu

        name: Test ${{ matrix.platform_version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}-latest
        timeout-minutes: 45
        steps:
            - name: Fetch Sources
              uses: actions/checkout@v5

            - name: Setup Java
              uses: actions/setup-java@v5
              with:
                  distribution: jetbrains
                  java-version: ${{ env.JAVA_VERSION }}

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            # https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-github-actions
            - name: Show GitHub Actions rate limit
              shell: bash
              # curl is unavailable on Windows
              if: runner.os != 'Windows'
              run: |
                  curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -i https://api.github.com/users/octocat | grep x-ratelimit

            - name: Run Linters and Test
              shell: bash
              run: ./gradlew -PplatformVersion=${{ matrix.platform_version }} check

            - name: Upload Test Reports
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: test-reports-${{ matrix.os }}-${{ matrix.platform_version }}
                  path: |
                      build/reports/
                      **/build/reports/

            - name: Save AppMaps
              uses: actions/cache/save@v4
              if: runner.os == 'Linux' && matrix.platform_version == '241'
              with:
                  path: ./tmp/appmap
                  key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

    verify:
        name: Verify Plugin
        runs-on: ubuntu-latest
        needs: [test]
        timeout-minutes: 45
        steps:
            - name: Fetch Sources
              uses: actions/checkout@v5

            - name: Setup Java
              uses: actions/setup-java@v5
              with:
                  distribution: temurin
                  java-version: ${{ env.JAVA_VERSION }}

            - name: Verify Plugin Structure
              shell: bash
              run: ./gradlew verifyPluginStructure

            - name: Run Plugin Verifier
              shell: bash
              run: ./gradlew verifyPlugin

            - name: Prepare plugin distribution upload
              id: artifact
              run: |
                  cd "${{ github.workspace }}/build/distributions"
                  FILENAME="$(ls *.zip)"
                  unzip -d content "$FILENAME"
                  echo "filename=${FILENAME/.zip/}" >> $GITHUB_OUTPUT          

            - name: Upload plugin distribution
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ steps.artifact.outputs.filename }}
                  path: ${{ github.workspace }}/build/distributions/content/**/*