name: "Update Webview"
on:
    workflow_dispatch:
        inputs:
            webview:
                description: 'Webview to update to the latest version'
                default: 'appmap'
                required: true
                type: choice
                options:
                    - appmap
                    - findings
                    - install-guide
                    - navie

jobs:
    update_webviews:
        name: "Update Webviews"
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                name: "Checkout Repository"

            -   name: "Update AppMap WebView"
                if: inputs.webview == 'appmap'
                shell: bash
                run: ./appland/rebuild.bash

            -   name: "Update Findings WebView"
                if: inputs.webview == 'findings'
                shell: bash
                run: ./appland-findings/rebuild.bash

            -   name: "Update Installation Guide WebView"
                if: inputs.webview == 'install-guide'
                shell: bash
                run: ./appland-install-guide/rebuild.bash

            -   name: "Update Navie WebView"
                if: inputs.webview == 'navie'
                shell: bash
                run: ./appland-navie/rebuild.bash

            -   name: Create Pull Request
                uses: peter-evans/create-pull-request@v6
                with:
                    title: "Update Webview ${{ inputs.webview }}"
                    commit-message: "feat: update webview ${{ inputs.webview }} to the latest version"
                    body: "Automated pull request to update webview ${{ inputs.webview }}."
                    branch: "webview-pull-request/${{ inputs.webview }}"
                    add-paths: |
                        appland
                        appland-findings
                        appland-install-guide
                        appland-navie
